# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6625322d0d45cc966ecb41ab9832ddc091427f4f5285af787becee87c88817276a4924cf421ff50dcccac3d685b1091196974a5b772ae6dfd342f13ed4092aa2

test:
  secret_key_base: 2f72457ab3452a01e0c1eff8410f0ac81105cafb65e778ac391a00b6d75a7557a6f7cb72368fe25b5fd7b41f7cd0233720546a48e7fef76ff5c0f223812e94c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
